name: Deploy to phoenixtri.co.uk

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip the repository
        run: |
          zip -r repo.zip . -x "*.git*"
      - name: Upload files to server
        run: |
          curl -X POST 'https://phoenixtri.co.uk/upload.php' \
               -H "X-Deploy-Token: ${{ secrets.DEPLOY_TOKEN }}" \
               -F "files=@repo.zip"
